name: 问题反馈 / Bug report
description: 反馈你遇到的问题 / Create a report to help us improve
title: "[BUG]"
labels: bug

body:
  - type: textarea
    id: describe
    attributes:
      label: |
        问题描述 / Describe the bug
      description: |
        清晰简洁地描述问题。
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: recurrence
    attributes:
      label: |
        问题复现 / To Reproduce
      description: |
        步骤示例 / step example：
        问题复现步骤：/ Steps to reproduce the behavior:
        1. 前往“...” / Go to '...'
        2. 点击“....” / Click on '....'
        3. 滚动到“....” / Scroll down to '....'
        4. 出现错误 / See error
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: |
        预期行为 / Expected behavior
      description: |
        描述你期望发生的正确结果。
        A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: smartphone-info
    attributes:
      label: |
        手机信息 / Smartphone Info
      description: |
        示例 / example：
        设备 / Device: Xiaomi
        系统 / OS: HyperOS 2.0.200, Android 15
        InstallerX 版本 / InstallerX Version: latest alpha/latest stable
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: |
        屏幕截图或录屏 / Screenshots or ScreenCAP
      description: |
        如适用，可提供截图或录屏辅助说明。
        If applicable, add screenshots or ScreenCAP to help explain your problem.
    validations:
